// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IconFluentAdd24Filled: typeof import('~icons/fluent/add24-filled.jsx')['default']
  const IconFluentDismiss24Filled: typeof import('~icons/fluent/dismiss24-filled.jsx')['default']
}
